apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: techcommerce
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
      name: http
