apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: techcommerce
type: Opaque
data:
  # Base64 encoded secrets
  # To encode: echo -n "your-secret" | base64
  DATABASE_PASSWORD: cGFzc3dvcmQxMjM= # password123
  API_KEY: bXktc2VjcmV0LWFwaS1rZXk= # my-secret-api-key
  JWT_SECRET: and0LXNlY3JldC10b2tlbg== # jwt-secret-token
